import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// ── Initial Cities Data (from src/data/cities.ts) ────────────────
const CITIES = [
  {
    key: 'novosibirsk',
    name: 'Новосибирск',
    region: 'Новосибирская область',
    populationThousands: 1633.9,
    populationTrend5yPct: 2.1,
    shareAge25to45: 0.31,
    migrationBalanceThousands: 6.2,
    avgSalary: 78000,
    salaryGrowthYoY: 8.0,
    highPaidIndustriesShare: 0.19,
    unemploymentRate: 3.1,
    dealsGrowthYoY: -25.6,
    priceGrowthYoY: 6.0,
    monthsOfSupply: 10,
    businessClassPricePerM2: 228000,
    monthlySalesM2: 68000,
    annualDduCount: 14400,
    constructionVolumeMkdThousM2: 2700,
    sellReadinessRatioPct: 63,
    unsoldYearsOfSupply: 3.7,
    activeDevelopers: 32,
    top5MarketShare: 0.48,
    hasFederalPlayers: true,
    hasWhiteSpaceBusinessClass: false,
    krtProgramsHa: 822,
    krtProjectsCount: 54,
    hasMajorInfraProjects: true,
    hasUniversitiesOrTechparks: true,
    constructionNormativePerTotalM2: 88000,
    avgUnitSizeM2: 63,
    landRevenuePct: 11.5,
    infraCostPerTotalM2: 7500,
    dataAsOfDate: new Date('2026-05-31'),
    sources: JSON.stringify(['МИР КВАРТИР апр.2026', 'ZSRF май 2026', 'Коммерсант апр.2026', 'Росстат 2026']),
    needsVerification: JSON.stringify(['hasWhiteSpaceBusinessClass']),
  },
  {
    key: 'yekaterinburg',
    name: 'Екатеринбург',
    region: 'Свердловская область',
    populationThousands: 1580.1,
    populationTrend5yPct: 3.8,
    shareAge25to45: 0.32,
    migrationBalanceThousands: 9.1,
    avgSalary: 80000,
    salaryGrowthYoY: 10.0,
    highPaidIndustriesShare: 0.22,
    unemploymentRate: 2.8,
    dealsGrowthYoY: -16.9,
    priceGrowthYoY: 9.0,
    monthsOfSupply: 8,
    businessClassPricePerM2: 272000,
    monthlySalesM2: 82000,
    annualDduCount: 17500,
    constructionVolumeMkdThousM2: 3700,
    sellReadinessRatioPct: 82,
    unsoldYearsOfSupply: 3.7,
    activeDevelopers: 28,
    top5MarketShare: 0.55,
    hasFederalPlayers: true,
    hasWhiteSpaceBusinessClass: true,
    krtProgramsHa: 280,
    krtProjectsCount: 11,
    hasMajorInfraProjects: true,
    hasUniversitiesOrTechparks: true,
    constructionNormativePerTotalM2: 87000,
    avgUnitSizeM2: 65,
    landRevenuePct: 14.5,
    infraCostPerTotalM2: 8500,
    dataAsOfDate: new Date('2026-05-31'),
    sources: JSON.stringify(['НДВ апр.2026', 'ZSRF май 2026', 'Коммерсант апр.2026', 'Росстат 2026']),
    needsVerification: JSON.stringify(['krtProgramsHa']),
  },
  {
    key: 'kazan',
    name: 'Казань',
    region: 'Республика Татарстан',
    populationThousands: 1318.6,
    populationTrend5yPct: 5.4,
    shareAge25to45: 0.33,
    migrationBalanceThousands: 11.8,
    avgSalary: 91000,
    salaryGrowthYoY: 10.0,
    highPaidIndustriesShare: 0.21,
    unemploymentRate: 2.5,
    dealsGrowthYoY: 2.6,
    priceGrowthYoY: 12.0,
    monthsOfSupply: 7,
    businessClassPricePerM2: 278000,
    monthlySalesM2: 43000,
    annualDduCount: 9500,
    constructionVolumeMkdThousM2: 0,
    sellReadinessRatioPct: 71,
    unsoldYearsOfSupply: 2.9,
    activeDevelopers: 25,
    top5MarketShare: 0.62,
    hasFederalPlayers: true,
    hasWhiteSpaceBusinessClass: false,
    krtProgramsHa: 228,
    krtProjectsCount: 2,
    hasMajorInfraProjects: true,
    hasUniversitiesOrTechparks: true,
    constructionNormativePerTotalM2: 91000,
    avgUnitSizeM2: 61,
    landRevenuePct: 13.0,
    infraCostPerTotalM2: 8500,
    dataAsOfDate: new Date('2026-05-31'),
    sources: JSON.stringify(['НДВ апр.2026', 'ZSRF май 2026', 'Коммерсант апр.2026']),
    needsVerification: JSON.stringify([]),
  },
  {
    key: 'nizhny',
    name: 'Нижний Новгород',
    region: 'Нижегородская область',
    populationThousands: 1205.0,
    populationTrend5yPct: -2.1,
    shareAge25to45: 0.28,
    migrationBalanceThousands: -1.5,
    avgSalary: 77000,
    salaryGrowthYoY: 11.0,
    highPaidIndustriesShare: 0.20,
    unemploymentRate: 3.0,
    dealsGrowthYoY: 0.0,
    priceGrowthYoY: 18.0,
    monthsOfSupply: 7,
    businessClassPricePerM2: 310000,
    monthlySalesM2: 31000,
    annualDduCount: 6500,
    constructionVolumeMkdThousM2: 810,
    sellReadinessRatioPct: 100,
    unsoldYearsOfSupply: 2.0,
    activeDevelopers: 22,
    top5MarketShare: 0.58,
    hasFederalPlayers: true,
    hasWhiteSpaceBusinessClass: false,
    krtProgramsHa: 180,
    hasMajorInfraProjects: true,
    hasUniversitiesOrTechparks: true,
    constructionNormativePerTotalM2: 82000,
    avgUnitSizeM2: 63,
    landRevenuePct: 12.0,
    infraCostPerTotalM2: 7500,
    dataAsOfDate: new Date('2026-05-31'),
    sources: JSON.stringify(['МИР КВАРТИР май 2026', 'Коммерсант апр.2026', 'Росстат 2026']),
    needsVerification: JSON.stringify(['krtProgramsHa']),
  },
  {
    key: 'chelyabinsk',
    name: 'Челябинск',
    region: 'Челябинская область',
    populationThousands: 1196.7,
    populationTrend5yPct: -1.5,
    shareAge25to45: 0.28,
    migrationBalanceThousands: -2.0,
    avgSalary: 73000,
    salaryGrowthYoY: 8.0,
    highPaidIndustriesShare: 0.16,
    unemploymentRate: 3.5,
    dealsGrowthYoY: -24.9,
    priceGrowthYoY: 1.0,
    monthsOfSupply: 14,
    businessClassPricePerM2: 183000,
    monthlySalesM2: 36000,
    annualDduCount: 8500,
    constructionVolumeMkdThousM2: 0,
    sellReadinessRatioPct: 56,
    unsoldYearsOfSupply: 4.0,
    activeDevelopers: 18,
    top5MarketShare: 0.65,
    hasFederalPlayers: false,
    hasWhiteSpaceBusinessClass: true,
    krtProgramsHa: 349,
    krtProjectsCount: 78,
    hasMajorInfraProjects: false,
    hasUniversitiesOrTechparks: true,
    constructionNormativePerTotalM2: 67000,
    avgUnitSizeM2: 59,
    landRevenuePct: 9.0,
    infraCostPerTotalM2: 6000,
    dataAsOfDate: new Date('2026-05-31'),
    sources: JSON.stringify(['МИР КВАРТИР Q1 2026', 'Коммерсант апр.2026', 'Росстат 2026']),
    needsVerification: JSON.stringify(['hasWhiteSpaceBusinessClass']),
  },
  {
    key: 'samara',
    name: 'Самара',
    region: 'Самарская область',
    populationThousands: 1159.0,
    populationTrend5yPct: -1.8,
    shareAge25to45: 0.28,
    migrationBalanceThousands: -2.5,
    avgSalary: 76000,
    salaryGrowthYoY: 9.0,
    highPaidIndustriesShare: 0.18,
    unemploymentRate: 3.2,
    dealsGrowthYoY: -19.1,
    priceGrowthYoY: 5.0,
    monthsOfSupply: 12,
    businessClassPricePerM2: 200000,
    monthlySalesM2: 34000,
    annualDduCount: 7000,
    constructionVolumeMkdThousM2: 1500,
    sellReadinessRatioPct: 65,
    unsoldYearsOfSupply: 3.3,
    activeDevelopers: 16,
    top5MarketShare: 0.60,
    hasFederalPlayers: false,
    hasWhiteSpaceBusinessClass: true,
    krtProgramsHa: 120,
    hasMajorInfraProjects: true,
    hasUniversitiesOrTechparks: true,
    constructionNormativePerTotalM2: 74000,
    avgUnitSizeM2: 61,
    landRevenuePct: 11.0,
    infraCostPerTotalM2: 6500,
    dataAsOfDate: new Date('2026-05-31'),
    sources: JSON.stringify(['МИР КВАРТИР Q1 2026', 'ZSRF май 2026', 'Коммерсант апр.2026']),
    needsVerification: JSON.stringify(['krtProgramsHa', 'hasWhiteSpaceBusinessClass']),
  },
  {
    key: 'ufa',
    name: 'Уфа',
    region: 'Республика Башкортостан',
    populationThousands: 1163.3,
    populationTrend5yPct: 1.2,
    shareAge25to45: 0.30,
    migrationBalanceThousands: 2.8,
    avgSalary: 67000,
    salaryGrowthYoY: 8.0,
    highPaidIndustriesShare: 0.19,
    unemploymentRate: 2.9,
    dealsGrowthYoY: -5.6,
    priceGrowthYoY: 2.0,
    monthsOfSupply: 11,
    businessClassPricePerM2: 195000,
    monthlySalesM2: 37000,
    annualDduCount: 8500,
    constructionVolumeMkdThousM2: 2500,
    sellReadinessRatioPct: 56,
    unsoldYearsOfSupply: 4.2,
    activeDevelopers: 19,
    top5MarketShare: 0.55,
    hasFederalPlayers: false,
    hasWhiteSpaceBusinessClass: true,
    krtProgramsHa: 140,
    hasMajorInfraProjects: false,
    hasUniversitiesOrTechparks: true,
    constructionNormativePerTotalM2: 76000,
    avgUnitSizeM2: 62,
    landRevenuePct: 10.5,
    infraCostPerTotalM2: 7000,
    dataAsOfDate: new Date('2026-05-31'),
    sources: JSON.stringify(['МИР КВАРТИР Q1 2026', 'ZSRF май 2026', 'Коммерсант апр.2026']),
    needsVerification: JSON.stringify(['krtProgramsHa', 'hasWhiteSpaceBusinessClass']),
  },
  {
    key: 'rostov',
    name: 'Ростов-на-Дону',
    region: 'Ростовская область',
    populationThousands: 1140.5,
    populationTrend5yPct: 1.5,
    shareAge25to45: 0.29,
    migrationBalanceThousands: 4.2,
    avgSalary: 64000,
    salaryGrowthYoY: 9.0,
    highPaidIndustriesShare: 0.17,
    unemploymentRate: 3.4,
    dealsGrowthYoY: -17.9,
    priceGrowthYoY: 2.0,
    monthsOfSupply: 10,
    businessClassPricePerM2: 185000,
    monthlySalesM2: 65000,
    annualDduCount: 15000,
    constructionVolumeMkdThousM2: 3400,
    sellReadinessRatioPct: 80,
    unsoldYearsOfSupply: 4.0,
    activeDevelopers: 21,
    top5MarketShare: 0.52,
    hasFederalPlayers: true,
    hasWhiteSpaceBusinessClass: false,
    krtProgramsHa: 500,
    krtProjectsCount: 6,
    hasMajorInfraProjects: true,
    hasUniversitiesOrTechparks: true,
    constructionNormativePerTotalM2: 74000,
    avgUnitSizeM2: 63,
    landRevenuePct: 11.5,
    infraCostPerTotalM2: 7000,
    dataAsOfDate: new Date('2026-05-31'),
    sources: JSON.stringify(['МИР КВАРТИР Q1 2026', 'НДВ апр.2026', 'Коммерсант апр.2026']),
    needsVerification: JSON.stringify([]),
  },
  {
    key: 'omsk',
    name: 'Омск',
    region: 'Омская область',
    populationThousands: 1104.5,
    populationTrend5yPct: -4.2,
    shareAge25to45: 0.27,
    migrationBalanceThousands: -8.5,
    avgSalary: 76000,
    salaryGrowthYoY: 12.0,
    highPaidIndustriesShare: 0.14,
    unemploymentRate: 4.1,
    dealsGrowthYoY: -24.4,
    priceGrowthYoY: 3.0,
    monthsOfSupply: 18,
    businessClassPricePerM2: 175000,
    monthlySalesM2: 9000,
    annualDduCount: 2000,
    constructionVolumeMkdThousM2: 0,
    sellReadinessRatioPct: 55,
    unsoldYearsOfSupply: 4.5,
    activeDevelopers: 14,
    top5MarketShare: 0.70,
    hasFederalPlayers: false,
    hasWhiteSpaceBusinessClass: true,
    krtProgramsHa: 115,
    krtProjectsCount: 5,
    hasMajorInfraProjects: false,
    hasUniversitiesOrTechparks: true,
    constructionNormativePerTotalM2: 67000,
    avgUnitSizeM2: 57,
    landRevenuePct: 8.0,
    infraCostPerTotalM2: 5000,
    dataAsOfDate: new Date('2026-05-31'),
    sources: JSON.stringify(['МИР КВАРТИР Q1 2026', 'ZSRF май 2026', 'Коммерсант апр.2026']),
    needsVerification: JSON.stringify(['hasWhiteSpaceBusinessClass']),
  },
  {
    key: 'krasnodar',
    name: 'Краснодар',
    region: 'Краснодарский край',
    populationThousands: 1138.7,
    populationTrend5yPct: 14.5,
    shareAge25to45: 0.34,
    migrationBalanceThousands: 28.0,
    avgSalary: 70000,
    salaryGrowthYoY: 9.0,
    highPaidIndustriesShare: 0.18,
    unemploymentRate: 2.6,
    dealsGrowthYoY: -7.2,
    priceGrowthYoY: 5.0,
    monthsOfSupply: 14,
    businessClassPricePerM2: 218000,
    monthlySalesM2: 72000,
    annualDduCount: 16000,
    constructionVolumeMkdThousM2: 5300,
    sellReadinessRatioPct: 43,
    unsoldYearsOfSupply: 6.1,
    activeDevelopers: 35,
    top5MarketShare: 0.42,
    hasFederalPlayers: true,
    hasWhiteSpaceBusinessClass: false,
    krtProgramsHa: 400,
    krtProjectsCount: 10,
    hasMajorInfraProjects: true,
    hasUniversitiesOrTechparks: true,
    constructionNormativePerTotalM2: 76000,
    avgUnitSizeM2: 65,
    landRevenuePct: 11.0,
    infraCostPerTotalM2: 8000,
    dataAsOfDate: new Date('2026-05-31'),
    sources: JSON.stringify(['МИР КВАРТИР Q1 2026', 'ZSRF май 2026', 'Коммерсант апр.2026']),
    needsVerification: JSON.stringify([]),
  },
  {
    key: 'voronezh',
    name: 'Воронеж',
    region: 'Воронежская область',
    populationThousands: 1041.7,
    populationTrend5yPct: 0.5,
    shareAge25to45: 0.28,
    migrationBalanceThousands: 1.8,
    avgSalary: 64000,
    salaryGrowthYoY: 9.0,
    highPaidIndustriesShare: 0.15,
    unemploymentRate: 3.3,
    dealsGrowthYoY: 18.6,
    priceGrowthYoY: 11.0,
    monthsOfSupply: 12,
    businessClassPricePerM2: 198000,
    monthlySalesM2: 30000,
    annualDduCount: 7200,
    constructionVolumeMkdThousM2: 0,
    sellReadinessRatioPct: 48,
    unsoldYearsOfSupply: 3.0,
    activeDevelopers: 17,
    top5MarketShare: 0.58,
    hasFederalPlayers: false,
    hasWhiteSpaceBusinessClass: true,
    krtProgramsHa: 110,
    hasMajorInfraProjects: false,
    hasUniversitiesOrTechparks: true,
    constructionNormativePerTotalM2: 73000,
    avgUnitSizeM2: 61,
    landRevenuePct: 10.0,
    infraCostPerTotalM2: 6500,
    dataAsOfDate: new Date('2026-05-31'),
    sources: JSON.stringify(['МИР КВАРТИР Q1 2026', 'ZSRF май 2026', 'Коммерсант апр.2026']),
    needsVerification: JSON.stringify(['krtProgramsHa', 'hasWhiteSpaceBusinessClass']),
  },
  {
    key: 'volgograd',
    name: 'Волгоград',
    region: 'Волгоградская область',
    populationThousands: 1018.9,
    populationTrend5yPct: -3.5,
    shareAge25to45: 0.27,
    migrationBalanceThousands: -5.2,
    avgSalary: 61000,
    salaryGrowthYoY: 8.0,
    highPaidIndustriesShare: 0.13,
    unemploymentRate: 4.2,
    dealsGrowthYoY: -49.7,
    priceGrowthYoY: 2.0,
    monthsOfSupply: 22,
    businessClassPricePerM2: 170000,
    monthlySalesM2: 14000,
    annualDduCount: 3500,
    constructionVolumeMkdThousM2: 0,
    sellReadinessRatioPct: 44,
    unsoldYearsOfSupply: 7.0,
    activeDevelopers: 12,
    top5MarketShare: 0.72,
    hasFederalPlayers: false,
    hasWhiteSpaceBusinessClass: true,
    krtProgramsHa: 45,
    hasMajorInfraProjects: false,
    hasUniversitiesOrTechparks: false,
    constructionNormativePerTotalM2: 64000,
    avgUnitSizeM2: 58,
    landRevenuePct: 8.0,
    infraCostPerTotalM2: 5500,
    dataAsOfDate: new Date('2026-05-31'),
    sources: JSON.stringify(['МИР КВАРТИР Q1 2026', 'Коммерсант апр.2026', 'Росстат 2026']),
    needsVerification: JSON.stringify(['krtProgramsHa', 'hasWhiteSpaceBusinessClass']),
  },
  {
    key: 'perm',
    name: 'Пермь',
    region: 'Пермский край',
    populationThousands: 1026.9,
    populationTrend5yPct: -2.8,
    shareAge25to45: 0.28,
    migrationBalanceThousands: -3.2,
    avgSalary: 75000,
    salaryGrowthYoY: 10.0,
    highPaidIndustriesShare: 0.16,
    unemploymentRate: 3.5,
    dealsGrowthYoY: 0.0,
    priceGrowthYoY: 13.0,
    monthsOfSupply: 10,
    businessClassPricePerM2: 238000,
    monthlySalesM2: 34000,
    annualDduCount: 7800,
    constructionVolumeMkdThousM2: 0,
    sellReadinessRatioPct: 68,
    unsoldYearsOfSupply: 3.2,
    activeDevelopers: 16,
    top5MarketShare: 0.62,
    hasFederalPlayers: false,
    hasWhiteSpaceBusinessClass: true,
    krtProgramsHa: 770,
    krtProjectsCount: 40,
    hasMajorInfraProjects: false,
    hasUniversitiesOrTechparks: true,
    constructionNormativePerTotalM2: 68000,
    avgUnitSizeM2: 60,
    landRevenuePct: 8.5,
    infraCostPerTotalM2: 6000,
    dataAsOfDate: new Date('2026-05-31'),
    sources: JSON.stringify(['МИР КВАРТИР Q1 2026', 'ZSRF май 2026', 'Коммерсант апр.2026']),
    needsVerification: JSON.stringify([]),
  },
  {
    key: 'krasnoyarsk',
    name: 'Красноярск',
    region: 'Красноярский край',
    populationThousands: 1211.8,
    populationTrend5yPct: 1.8,
    shareAge25to45: 0.30,
    migrationBalanceThousands: 3.5,
    avgSalary: 95000,
    salaryGrowthYoY: 14.0,
    highPaidIndustriesShare: 0.20,
    unemploymentRate: 3.0,
    dealsGrowthYoY: -2.2,
    priceGrowthYoY: 5.0,
    monthsOfSupply: 11,
    businessClassPricePerM2: 252000,
    monthlySalesM2: 34000,
    annualDduCount: 13500,
    constructionVolumeMkdThousM2: 0,
    sellReadinessRatioPct: 55,
    unsoldYearsOfSupply: 5.2,
    activeDevelopers: 18,
    top5MarketShare: 0.58,
    hasFederalPlayers: false,
    hasWhiteSpaceBusinessClass: true,
    krtProgramsHa: 130,
    hasMajorInfraProjects: true,
    hasUniversitiesOrTechparks: true,
    constructionNormativePerTotalM2: 86000,
    avgUnitSizeM2: 64,
    landRevenuePct: 11.5,
    infraCostPerTotalM2: 7000,
    dataAsOfDate: new Date('2026-05-31'),
    sources: JSON.stringify(['МИР КВАРТИР Q1 2026', 'НДВ апр.2026', 'ZSRF май 2026']),
    needsVerification: JSON.stringify(['krtProgramsHa']),
  },
];

// ── Seed Function ────────────────────────────────────────────────
async function main() {
  console.log('🌱 Seeding database...');

  // Create cities
  for (const city of CITIES) {
    await prisma.city.upsert({
      where: { key: city.key },
      update: city,
      create: city,
    });
    console.log(`  ✅ ${city.name}`);
  }

  // Create initial macro snapshot
  await prisma.macroSnapshot.create({
    data: {
      keyRateAnnual: 14.5,
      mortgageRateAnnual: 22.5,
      preferentialMortgageRate: 6.0,
      inflationYoY: 5.4,
      realIncomeIndex3yr: 1.11,
      unemploymentRate: 3.2,
      medianMonthlyIncomeRu: 64000,
      medianPricePerM2Ru: 158648,
      source: 'ЦБ РФ, Росстат',
    },
  });
  console.log('  ✅ Macro snapshot created');

  // Create default admin API key
  await prisma.apiKey.create({
    data: {
      key: 'lvl_dev_key_for_testing',
      name: 'Development Key',
      tier: 'enterprise',
      rateLimit: 100000,
    },
  });
  console.log('  ✅ Dev API key created');

  console.log('🌱 Seeding complete!');
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
